#!/usr/bin/env bash
#
# open-pr.sh — takes the working-tree changes the agent produced, commits them
# to a branch, pushes, and opens a PR that links back to the issue and carries
# the agent's "what I tested / how to test" summary as the body.
#
# Required env:
#   GH_TOKEN       token with contents+PR+issues write (github.token in CI)
#   ISSUE_NUMBER   the source issue number
# Optional env:
#   AGENT_SUMMARY_FILE   path to the agent's summary (default $RUNNER_TEMP/agent-summary.md)
#   RUN_URL              link to the CI run, appended to the PR body

set -euo pipefail

: "${ISSUE_NUMBER:?ISSUE_NUMBER must be set}"

WORK="${RUNNER_TEMP:-/tmp}"
SUMMARY_FILE="${AGENT_SUMMARY_FILE:-$WORK/agent-summary.md}"
BRANCH="agent/issue-${ISSUE_NUMBER}"
BASE_BRANCH="$(git symbolic-ref --short HEAD 2>/dev/null || echo main)"

# Nothing to do if the agent made no changes.
if git diff --quiet && git diff --cached --quiet && [ -z "$(git status --porcelain)" ]; then
  echo "No changes produced by the agent; commenting on the issue and exiting."
  gh issue comment "$ISSUE_NUMBER" --body \
    "🤖 The agent ran but produced no code changes. See the [run logs](${RUN_URL:-#}) for details."
  exit 0
fi

# Identity for the automated commit.
git config user.name  "${GIT_AUTHOR_NAME:-agent-bot}"
git config user.email "${GIT_AUTHOR_EMAIL:-agent-bot@users.noreply.github.com}"

git checkout -b "$BRANCH"
git add -A
git commit -m "Resolve #${ISSUE_NUMBER}: automated changes

Generated by the ${AGENT_CLI:-agent} CLI from issue #${ISSUE_NUMBER}."

git push --force-with-lease -u origin "$BRANCH"

# ---------------------------------------------------------------------------
# Assemble the PR body: agent summary (or a fallback) + provenance footer.
# ---------------------------------------------------------------------------
BODY_FILE="$WORK/pr-body.md"
if [ -s "$SUMMARY_FILE" ]; then
  cp "$SUMMARY_FILE" "$BODY_FILE"
else
  cat > "$BODY_FILE" <<EOF
## Summary
Automated changes for issue #${ISSUE_NUMBER}.

> ⚠️ The agent did not emit a structured summary. Review the diff and the
> [run logs](${RUN_URL:-#}) before merging.
EOF
fi

cat >> "$BODY_FILE" <<EOF

---
Closes #${ISSUE_NUMBER}
🤖 Generated by \`${AGENT_CLI:-agent}\` · [CI run](${RUN_URL:-#})
EOF

PR_TITLE="$(git log -1 --pretty=%s)"

gh pr create \
  --base "$BASE_BRANCH" \
  --head "$BRANCH" \
  --title "$PR_TITLE" \
  --body-file "$BODY_FILE"

PR_URL="$(gh pr view "$BRANCH" --json url -q .url)"
gh issue comment "$ISSUE_NUMBER" --body "🤖 Opened a PR with a proposed fix: ${PR_URL}"
echo "==> PR ready: $PR_URL"
