#!/usr/bin/env bash
#
# open-pr.sh — takes the working-tree changes the agent produced, commits them
# to a branch, pushes, and opens a PR that links back to the issue and carries
# the agent's "what I tested / how to test" summary as the body.
#
# Required env:
#   GH_TOKEN       token with contents+PR+issues write (github.token in CI)
#   ISSUE_NUMBER   the source issue number
# Optional env:
#   AGENT_SUMMARY_FILE   path to the agent's summary (default $RUNNER_TEMP/agent-summary.md)
#   RUN_URL              link to the CI run, appended to the PR body

set -euo pipefail

: "${ISSUE_NUMBER:?ISSUE_NUMBER must be set}"

WORK="${RUNNER_TEMP:-/tmp}"
SUMMARY_FILE="${AGENT_SUMMARY_FILE:-$WORK/agent-summary.md}"
# The "Prepare working branch" step already checked out agent/issue-N (fresh or
# reused for a follow-up), so operate on whatever branch is current.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
BASE_BRANCH="${BASE_BRANCH:-main}"

# Nothing to do if the agent made no changes.
if git diff --quiet && git diff --cached --quiet && [ -z "$(git status --porcelain)" ]; then
  echo "No changes produced by the agent; commenting and exiting."
  gh issue comment "$ISSUE_NUMBER" --body \
    "🤖 The agent ran but produced no code changes. See the [run logs](${RUN_URL:-#}) for details."
  exit 0
fi

# Identity for the automated commit.
git config user.name  "${GIT_AUTHOR_NAME:-agent-bot}"
git config user.email "${GIT_AUTHOR_EMAIL:-agent-bot@users.noreply.github.com}"

git add -A
if [ "${IS_FOLLOWUP:-false}" = "true" ]; then
  COMMIT_MSG="Address feedback on #${ISSUE_NUMBER}"
else
  COMMIT_MSG="Resolve #${ISSUE_NUMBER}: automated changes"
fi
git commit -m "$COMMIT_MSG

Generated by the ${AGENT_CLI:-agent} CLI from issue #${ISSUE_NUMBER}."

git push --force-with-lease -u origin "$BRANCH"

# The original issue is encoded in the branch name (agent/issue-N); the number
# commented on may be a PR, so use the branch to build the "Closes #" link.
case "$BRANCH" in
  agent/issue-*) ORIG_ISSUE="${BRANCH#agent/issue-}" ;;
  *)             ORIG_ISSUE="$ISSUE_NUMBER" ;;
esac

# ---------------------------------------------------------------------------
# Assemble the PR body: agent summary (or a fallback) + provenance footer.
# ---------------------------------------------------------------------------
BODY_FILE="$WORK/pr-body.md"
if [ -s "$SUMMARY_FILE" ]; then
  cp "$SUMMARY_FILE" "$BODY_FILE"
else
  cat > "$BODY_FILE" <<EOF
## Summary
Automated changes for issue #${ORIG_ISSUE}.

> ⚠️ The agent did not emit a structured summary. Review the diff and the
> [run logs](${RUN_URL:-#}) before merging.
EOF
fi

# Create the PR only if one isn't already open for this branch. On a follow-up
# the PR already exists, so the push above updated it — we just add a comment.
EXISTING_PR="$(gh pr list --head "$BRANCH" --state open --json url -q '.[0].url' 2>/dev/null || true)"

if [ -n "$EXISTING_PR" ]; then
  # Follow-up: PR already has the "Closes" link, so just report what changed.
  cat >> "$BODY_FILE" <<EOF

---
🤖 Follow-up update from \`${AGENT_CLI:-agent}\` · [CI run](${RUN_URL:-#})
EOF
  gh pr comment "$BRANCH" --body-file "$BODY_FILE"
  PR_URL="$EXISTING_PR"
  echo "==> Updated existing PR: $PR_URL"
else
  cat >> "$BODY_FILE" <<EOF

---
Closes #${ORIG_ISSUE}
🤖 Generated by \`${AGENT_CLI:-agent}\` · [CI run](${RUN_URL:-#})
EOF
  PR_TITLE="$(git log -1 --pretty=%s)"
  gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH" \
    --title "$PR_TITLE" \
    --body-file "$BODY_FILE"
  PR_URL="$(gh pr view "$BRANCH" --json url -q .url)"
  gh issue comment "$ISSUE_NUMBER" --body "🤖 Opened a PR with a proposed fix: ${PR_URL}"
  echo "==> PR ready: $PR_URL"
fi
